sudo: false
dist: trusty
language: node_js
node_js:
- stable
branches:
  except:
  - gh-pages
addons:
  firefox: latest
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
before_script:
- npm install web-component-tester@^5.0.0
- npm install bower
- export PATH=$PWD/node_modules/.bin:$PATH
- bower install
script:
- xvfb-run wct --skip-plugin sauce
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then wct --plugin sauce --skip-plugin
  local; fi
after_success:
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then openssl aes-256-cbc -k "$DEPLOYSECRET"
  -in deploy.enc -out deploy_key -d; fi
- cd $TRAVIS_BUILD_DIR/scripts
- chmod 755 ghp.sh
- "./ghp.sh"
env:
  global:
  - secure: SsSiGzkW4zojxBAvQHOgz0KiNX+UY0DQO6KrcCcsgOTK/OmxTTlc++mTBENI5FwfSa1ADQQH0VjlZIfvC4Lfor6pPTpKoS0YPdoCE5AVy2vlJM/Ftp8z6AjF1hTbLntgTPZVvg7oNwg8zAvKNatbVRLC26jUwqEL0xnbAk/XAbevj1JLslK4vVM9be/7ZAOm6pSXZIcUhg0FHEtv+o7MXmZduRTczae0NOtPOMhE8hKVeHmey8IuJHojcrp4gq2gwgGWlykwTwbqWjD+fLRrICT/0wdPXRcZiOVkJjUrWdyC2ZyjHtYCTlmZ5OpS742Czw+pLeJH7JiJE4WrZKsEqqTJeDB1/3MZNsnVCIVdv83bOwUyhVCGxKCjIlVmM+fejMAIv6yMgHMPDaIW9e2Sz0qcfInOLlJs6V1IYjuRtJTwpxFqnDFT2An9py47iDCUsSF9HPzg7GrqggrklgrJ/OFCG2eH708JU8KLfL11isqtmh5tp0h0OYyI/FN6Pee2kiILkppB/cQndAKc0gW2C5ugPmzZX96lK6QU7MCZKQuYDX8wtJ8EXtApg8cdSz7Exso2ay+qIwnZIrtm/C0Jhp2rM0rh0qw7qAKd3y/0phDsU84soPgXS8Xa3TvsOExCegj16VqrnJh6A2WJ9dIkw+RciK9WASVXqrRbXyx+JFE=
  - secure: VUeO/TgSJ1DWEOnkp0TJbocdGJN3Vahv0gaXgl6EVL3Kddv1H2iBsUI9FGHURPQNw1OKJRLWcHJh0QycN7BlfpRQGArRIyTO2J34NRZEbuhCpJxOIjbBKwrSrXecu3FvyWG/zg0n+n2Qji8WFD26uGU1LkrU/TYECAirt6K6pkmzd+Kxotw6wNRF7DWFyBt3g/VUmjguMJCrri26cRXeNEI9Xjnkocg2I3CFZ/WPzAzyrPA0NKKT/nOANCWEIJNAiPFRG3pgLHNZj9SiG6mjGUUPtF3pSKdBhWG244UNN9k6YkjaSZ4zbPY3kxTxFTZrIpctZiVwpPR/OxUCPje+cWisJstSp+tjW4QSh8UHF0rF3NSf8BzSNDp26al0SYU7qj4d5CiZXv8CP2MyPUpXuO2uYec9+bFZ50KF1iONmN/f7teKDHRYdJClogd2UZ+VKjnWZ7rNBJam2IRBqxSx4kR3sfOlEbKb0Cn01+TPPUFt3Cp78QSwToMqt4iNyKh52krEVo71p+tsS8mKOBULYqIodsU8P0u1DVVmlJICFJZzEemNbfBRiwdlf2yh6+6zi4iKVVCgayeG5rDNzFivdSA0BU7dviBiOcH5U8wXUr0vzxxxMxCbj+c9pP5t1A4C9S75lT6RgzJ2Fw6SdLFNoOiQpy13IdiBZ0giL7goghM=
  - secure: gT2GnGqXtPt3DQpYmhlJjU/rZOEJPF7M1B+hv0L1eGmNgrLJrWy09WIdj+Sh0csH3pu2/TFGqaDIAFel3kG54dtB4WHdZhmnV0RyG/bjMO/hafb7Ya7sZAw5XLcy1cLuYaJ4Z2J3V3IldDSxTYF7PGBua5OA5wJAyE4j7tJ5rcjSr9W7wPXOdZL7vcBOX0Ndnu0Gyyxn2ezh4gAeOU3mdT9iK7kV13JU4qjLny4kpsAhGO5BwKxYAWxjlAL0lQeXj9IppZkMmkWLlR3do83EbqxgeSm/Sx4Pdpp8wtPpiMEKoGQ6URRCM+cx4OrKcHwnmiuK7cOj67OyHYJ5eLiv4r8P/6hGgqDjzT3WlzB6jiJ3XoSoIhKzgjPlVC8loyfZkGSW1+mYiIJ4J218SSJCUjeQfabuVelj6ICn3ouzNlcx2nc46Lr8eL2pdIqdNZ46p3+dSsUlWQHE+3sC1ORVxgNQwtpTqEPm/bCdX9TsXLMu/56aoOmBzrQw1K7n9ivKVHeKk3q7A5cooaJqn3KSIKT8OKNMx0GIeAyGDTqBA+XSF3dwGjdM0obDp+lW3ggTWu1elfSuMlupc1tFRip95RKVtF3jjYX5yDkxcawcrUQWyM9pJnH/EqOdPbljMxF+/oqO7ZyXgOvlOYDRPtAKWHcKypCVTdLObFB2fDx2VHc=
  - secure: aT2YRFMWjyhFCMGhmgP3Zgs4o3e4QJx+FmjofINcoBeaoIfha/GMhq9Tt4hf7Mo6VllMDVNyjo2YjSuWhR0Pt3CAuvloQWe03iAHOAt4xHbn/ck0RtDu3Uo/w/b1QBY2TRvm9H5YTzq6qQDvGSjjYB56uAn+drzDAFDP1b3nRY4TRuyJPmEhb2UQtj9I6crYBpYyRBKHMcbZDewtGN6DBlUUS092qWGd2T3r8ZjbFa7WO45IiwP25ikpILwNIpwU4vJJjeibt3btgc+rBsQp5VwGyo92Q30cWwWK8obc9EwaOhCn8rGnRSZ7iTumCH2e50iLNjAYUA1MNvNU1OvGBUH6Nl4rhF22+8vYEakT6n6zC+0C5hydnrsVt+No1sB/5jySxl6rFTjDKzNS4hN72jugmy50aS4j6WK+aWE+xPAku5ZLv1GCN3G/g5jltCvgvsscIp7IDI0W6jzwTLVOwQWKZgvvRdBSU0XHbUeiqwxAY6OKf4fck3s44k2FZFlauyZLP6dC302r1vjsbdklpnuSbrvSp1a3XgNPrqUJ/D2d2IvxnftpddwHTTBVDjdM8liCgiejiVmKGRlAPFFmiijwA3S8bnrJF5cSUMymDyavgvDOk/shGwKA0InZf+vONaJVepN5Q6X+aVHgPIu/tdWxDdRI3vdZtqDqNDMpddQ=
  - secure: LMMdsYLuoIXkfQ6oR8dOFtC2qDazw3BPjwSeLMrb4loGi6eOslI4IcIIEZEydjlo9AIQjfxvlZ8i7cl3eeMofq8tsGB/kWaIUwL3fKxYyaXJdZF+Gj6NVy/bWzfsOnYqF9koFasSqhZMVZI0EAH5yN67DUQMSzl/gBOgURCsO/kdLGyFmRxUhYYm3EACXookYN0Etlh39nIyerTu6t1ABS/sssTTPXKliydOJfRqLT49qTqRAwrlKiZ/Z/mx6DoEKzX6WB1bTtq0AzLCWFl0VuDtXxeLHLBMmu1IOAB27nDoUaA3dUhkbmXHRUEdp0x0WdGelnQ1mh2NQyFCKW0WwvoWowWD7AKnsjTUJoA+DlxRLQChHfHMSkeaNiihMavu4ckCMDJfg0Y9JM/tdNH0oc0svF+x7ErQcagxWCIUQBwWfpo7I38ayTXQHe3nJ22Y+w9bFMuo5y9dGQr8QMn97mCEqu9oLYKMU4v4N+NKUD5UzXjrSs0vP7HcO5pb09yGfUBFQxrdWOuBIJ+0ZCOELoWnsG6tZh2BbTfQRgdVLDzB0J7keL7CpGPkUhwOT3rEfdT58Nbe4pxAEHanIp3vO5/dWzCLtygxI//pBqqFMkauIxSnT6otAa4Hp5qlILWGQNnfBWH7brtvg5lmv62ickPbCeSxMTGyz0XHaLEHxMM=
