sudo: false
dist: trusty
language: node_js
node_js:
- stable
branches:
  except:
  - gh-pages
addons:
  firefox: latest
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
before_script:
- npm install web-component-tester@^5.0.0
- npm install bower
- export PATH=$PWD/node_modules/.bin:$PATH
- bower install
script:
- xvfb-run wct --skip-plugin sauce
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then wct --plugin sauce --skip-plugin
  local; fi
after_success:
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then openssl aes-256-cbc -k "$DEPLOYSECRET"
  -in deploy.enc -out deploy_key -d; fi
- cd $TRAVIS_BUILD_DIR/scripts
- chmod 755 ghp.sh
- "./ghp.sh"
env:
  global:
  - secure: o4iP/as91gEMVJdxzd20LgIAe1UU14hR/7cr6Nv9b5xZ7VaSXyF7JhIe+hVYDmv7iLc1tVaaOgjU76uLUBupLeIeXhzJYjySTZutxQu0b/+HlZAUWKOjYG85MkEJ1nJfZ4AlGYwrROGnp/DnHnU2YEvDAeYuB68MIZf+LCL3Eb+bPvyysJzncN3hqDVt8tMhcgU2hgICOHuhMWRR9sb4T6TQa6e4Bj6eKkZV0vJjwGALvna/I0FQEUfGI+IWc0SxBhxYnqrTmNh5NwXORh9opF8TTG+gSi3eg39CnCPrYLwf7/0/q7aERSDbw0OSiokWHZqhAQI6/j/2gp0ZM9fYyoTvmCAB1LshpSkr4iN1950TR65OUBg02UPGr512jlWnSv3tnKUk99aP6R5XU+ZXNSwG7HU/7nNduyvagYWcMTY+8ZzeXQwXluyzK8owlO5Ee4r1mw+l4+gynm5wAVjj8qoWLgn42nUokJ/JHmP69Jpq+gE7WEv3oWSM8kO9vHr/3KnZtMWTnxTCUG338ptusj/XD0oduKYlSzFkAhLArz7qi8KsvBNwIj2wcpOz1bYiza05K0MaULb1A788AJWWnq7fj5RRT/DY1BCgB8hiKoquLWL5vYLMNXYh3ap/GSvaUEAfQkaDBFc62pBXvsjQN6eZxGxb3ojoNpljfrmcyn0=
  - secure: F+agMbXfUV8EadDvlcedrnOOZBnDLng5dQyGc+s1wytKhKm+ZRwbTGEsDetzZjrq8QRN+3svyUefi6dTYJlMvlVct6v4P/9O4RJ7VZu8TceAkz+rb9EmsyRppyms0ODNWs3SxQCDofEuuG4n0UKLa5+AY/3Fl1tqb2sgItTLB7e25BVjKoaMUMwPQMcyfv5L6s/eSlOYVzPnfINPhdj3ugAe0u0LVs/rSCFtraT/gwecRPVoM1L2kN8dZHivvyGEz1W7WIH5lnXuDD9Dt6NWhDeaZdlWQ1pR6YeBRhYHTCDrvup0tjL+m0+F3WATbzdWO0nZULZmZFaSgHSdWkHb16N76HmrocDHlHqB6ChJhZc0rb6VCNjXoowyPPRT+kF0IrsDsCzB+awHhIaKZ92bJNJoWHN1LsTJrO3C+g9unOeghiC4fEkYzTyqX0TbWV2CqWHFQJDhp6pkgOr4r5TNhZE6h83NFFmb0o4ofMz/Y7cOt/sh/DKJSy8M2dP6ZFmy0HGonpjQGHbIFyj82eMutZIqk+5jc66zRYAZQaI41Zfl19LuVRUvJvAiIqgVLEz82mf+/lwkLklzdnH3YuqLkA9oBftQv5C2zpjGcmg10Wcv3cRg2iGLS6Kk8lmse+fc2NRWkzLlxs58LnNr/Qbt3Qn3xgvLZQEMCU+9z3ccm7o=
  - secure: CRJ79jf9Q2DC4yR/IY7xhM0Ex3xuSdf18AhAYeJFpu7PMC1/RI8bYrXcAv0cwb7jq9a7oV6lJLzAEEma+5JdzQMaQ24gsAX9+Ea9AclkN2YgOQDvsyicDUQTRSKoEW4rORzqtasVhpE1N7at2seTC8+H0oLUOkUZud+M3VcVQGKqgugum6QCVoJnUakdiMU6mlf2837Duki0A+kF3C646hOIzXQJ00pxpqplwgXa6uXJBeVIicsthP6R62kyQswuo8BKQMDXNwyK/RqzFAJzb1GY0Eoei3JeVRyQRF4gKo9KW/vjvAJhAgkudTO0KvWG4R4npWNPAe5IlTDtIYOTjjMktvULJXk9wgViP3Nnvvk+gZ+MMP0AjPRdn9mIortR2WjUbPxLG8LB4M84sjK5pOCM/7Wu1X36nQnPWEmO6h8QSMDqyqI1l/PiRsxnNu+kh4Fj45CP4ZpkbiuwztHOpTcmRwvDg8utEyBup+AczWKeZq2JIRm2InrQP0G+ngaPbWzP0KdlFWxNqeF6G/Wcu8KmpPpCEP1djbanqbG4+SxwX6e1Tg801dVKOiRygEnAzozW7ZKbGj0HxlLsbAl92AioLA0F9l6TeqRYWFicJOSCCeRcgxErsBUWEwymEnuh29IVA/YtnNt96+7YR3VIW38j8h/qZ+XuJIrJ63PivwY=
  - secure: Wloi4M+i8asdK5N3o81+aOMzAk7YCCW+LJ4OdvdYWOToM9YasgLRmDHKjmgjtNOLZ1maHsXIadcdheryGEU0zURThmOt4zCqa8bs8zlpCLA1IR3BpJ9itSkUoFQbpfKkZjtMKGT+XQO+Ge/K7lucUO4O/FyjEEV1vMLYoy9CUHRiKfi0RRhAdQ2TSR4c9H2xiP0q42rxsVFkW1SrjX9cjZ3idCWC+r7wdWkt63e6JhnGpJoMiDEtozPxsEFxkEBb1v7E2bCIF/luQc2GA2U1YDsGm+LThyxCCa9fO6eVUozrKYbtM5UmN9uY56I6RQmBtl++lKyRezGqvk/jeBx6x8ybZ4AweAYf2UDQrBnUx2zK8VsQ6/Vb4drSlPHaMK0i5D5vo4vE0vg+0ofHpTjrnbUvuwyvF56x7hF6WoRQqkPg4iBIG1HCZYxdGKol4W1ioIYkZ1xkExCpeuS3oDvqga5z2CgV09PYvxOqx7KRcakuivlajporpmm8DNLwT8ce5otODR+Cf1vgd1+v6lvyl+Re1QNbsPVM+ON4Rirg4CpuGYIIw0kDc7ItG4ClPZkNcVSnlmMAQnQpRSkL16A6f5Zz2xTOD3cTkw8CnM7d5KqhxzVwqCTTdYz5jbophBxZkrayLukF5NyjYbX+LDOjYSQ472tGgHE9BU4vgtIsExI=
