sudo: false
dist: trusty
language: node_js
node_js:
- stable
branches:
  except:
  - gh-pages
addons:
  firefox: latest
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
before_script:
- npm install web-component-tester@^5.0.0
- npm install bower
- export PATH=$PWD/node_modules/.bin:$PATH
- bower install
script:
- xvfb-run wct --skip-plugin sauce
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then wct --plugin sauce --skip-plugin
  local; fi
after_success:
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then openssl aes-256-cbc -k "$DEPLOYSECRET"
  -in deploy.enc -out deploy_key -d; fi
- cd $TRAVIS_BUILD_DIR/scripts
- chmod 755 ghp.sh
- "./ghp.sh"
env:
  global:
  - secure: XUZ/vLsF8TN52jwOF4+wXOzzg5iWZpiUelVnJfv2uKqsHgOlpDo0yFgZ74mqghjNUcU3WNdBZY+mV0My3Jt7U4oy9HSQY0CURggfQdis8U2nFzFAYIUphV2XNDCw/JX3GEKAV5jlnO2aqQjg+4OBPhsE6ms1GbSHksUsLHvtwa73/nrS7E9cmHZSEO5XlNUsUTC7NmkiFD3G0RLUFd5G8unX/eoz/v/E1ZnqTgLt9yza9oitb3DkmSoQMJhYurrlDyCYmCHaL3L98dfrFOtuOmJIe4MQfuFi1eO3gGAIF/fup1ZHqRosBOo5kDuUpcaGTpOHpMtbySo6xxqUiQE8tDzyd/cWoI/r4i8p3+YSMJ9Cslek/xrL4SfcOw7rJCoQZdIZ0wrHe6TtD0ufXX7vEJpdgTR4GZxRioe1bebwtfCsVPJzP+pyxgYSBG9JDeWhJ7rJCtwPvjj1JgCpcuAl1i14UrRryjhEZORWqvKaUATjYhv5f3t6FJ2MDDIRxMuYaOk2OspgUIjON4DbBfZ+ko1wwybeonyjl2ocH70v8JkqHUsYmTmURfZ8jg8mlvITGof2uPyGWxIVB8IHRcU5aLYnjW3TvaZT6bqOHMMoA0Q7wei2ZRMKeYWCRkDasfX+S5Z/9WyO5napPSQ+BQERryiYZd6jfl0eulqTyRLSN7o=
  - secure: jATev8K8YNR62wIzDUp8jKrt5xQ4PgrwYRte17qXJDCAuLeAILhIrAMcb4AMs+5//AtFb1sWw5ULb8GyTBw0jSptx0jazwOnuOW0aG4BiOmQvz11YkA3qm+ynPsStl3N2/K2wumbbPO8v7U9by3I+qAoPjhQPpd9iHQg5UKuQbtdRZshUZ52bz9KiLpu4v9VXTs9EihqalFaC9ZLz+dkGduGmUfNqP65A8KTudKXWExKR0nZ4UUojoE2BJiZuiQ9z+tjIXr8cm7TJ6WdoVs7TT4rYSyOpS338O0nEOqi6S0Xc+I+wHo/skDhxdhTfg/GnaHYaZdDW29XdH/33bKm8JMUGwtYb2aKNtGxQfgK51scz0kUQIzod1+nahdU5rk/O7WkmPt52IWCMQWgpdNiahU23XooLR4j5BVKTeXDZ40QmuWQqRp52LUVyKM4dSOPoLpKY2ReZ9rN4UomjNb4zfY/8kOHL15HU49zWY+f9/N3HXAKCmcswOPvtd8PV7HJd7UNzi9hsS45xeIxEa/eqHpj2kNsf6ZtB69cHakxIgUNBDFHbs5MbAL96jhl8FQTkLbwoLIlD/YTFYrcVlLvqlwOf8djTBHkMQOmETGZ8dnoLuSPdzcUDcc/4cL4dpgShh0D8YMrSXVw65hUeV5svnZxCRatlg7+dwznH1LJKUU=
  - secure: hJKGfj/a2g1QBDDlBs3ORdwf0cTypC8GnYgc1GmVvFo+0tDXU9XM9LtntidgVWcHJTza8vXKtVcioQWtg+pjsHezwzRc/iEp2Tvv1nuFM8NibzNSq5g7uz4nBijXo1FZp9VLzM3vGYrJQS4Vdw8HL8Mpfe4QGWXfwhkLh94H4GtG0qv9Jf9obEVBWu8yv+C/GkBtrrxKGr7NGsLuGjqn8/1xLIsvdgo0dPjem8+5JjW2pP6wuKgfuige16XmBuZZeWlW5EA5Z29xrpcyQCJ+rCD8+8aDf4aoGcb6gNa/apuE1VbLDm4sYRdVCXZWz4zC2VcKLtWqSfDKbXbDZqxS0rWYbY6gEBWMVxpa22yrobE++lmsqtIiWrCO3pNoyvC1X/hXWbjCi9EbAP00GhE7cgKeAtxLWJDQkWzBoNVJtNSf0tBjEutqxl5Iqxo7x7AMKsEurqipmHKjvLTDnbyIhy5PREV6j2QRJzZHFd7TyhhLAUkkz5DM+lreUOzqgdp9nPfgOAN5MNH7j/TylyTPFjoWxFFqK02ikr4cDRFgqCXWBcLQrxmePVPC02X2lIRL9O2C0lZWELgvxdjEdzX/kPrHdKgEnsO1aWybKVwv5nDpS/riOAw95ZSqjvdtfYa86bfOFEOi0husEu0HOeW0BFTCyN/3T+9N+aVav3Xsdvc=
  - secure: p3vZ/8IS7qIg0WyMVdF5/deWoUrz3wal+q8piBEimXoMAPUb0ZxDrXb3vBGn3GDp5tyuiQCP6HPi4t4mRLDS04lfn0zUt83JZXcERu9Y2jB6UQDg0hZsVHkrIWOvzINXJX0ERo8mIxkxYmQ8DUduj1ZVwaKDD8qJuF/N8v+5p8oaY4kL23NHgBxIpJNhmHwWBHu9aI3uggJLpqeaiAx7Tr+7WnTlHaHuPgOSimsMpSYBkLOJwIE63lxiiN/14OY+M8KrkbTa2JMG/zKBLwb6EDLSDGEFaM0oIS2dTikI6WhWV1QKxFJxHPD7VCHY2uj64TyAv1ylfcNQJrJfy0jGx/fN0sQRDfcv53yuzyq7rTs3Na17tQP2VIedgSKGEFNHr5hok97Q4ce0T0g4/uuYfF3gnZOQU+8HbFPasok0htcnxaCm6PkScJhv+Pa5yDEu8BU82pV44mUaBjbN6GNQB7ZpasKmcASDzffsa37/RsUdGfE5RlE+oGTTZXJEWA9cWwANJwW29jaK0quQbNDF7B9pYmNI2wguv3fSqhXa26pLExOksYiPm7OmTEhauGzfUkaxaFtnZ2R2p9yDZNLjmx5CxX9vwbNXxrIAd7UALqTh91ff6dzWdKtpiMKJ1rK1x3TO2YzHs8KaCrT1bjqqmxJKzhOLtsGOA+joSLkb85g=
