sudo: false
dist: trusty
language: node_js
node_js:
- stable
branches:
  except:
  - gh-pages
addons:
  firefox: latest
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
before_script:
- npm install web-component-tester@^5.0.0
- npm install bower
- export PATH=$PWD/node_modules/.bin:$PATH
- bower install
script:
- xvfb-run wct --skip-plugin sauce
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then wct --plugin sauce --skip-plugin
  local; fi
env:
  global:
  - secure: M4H7T0rkD373JAHVwErH1ceKU8QC8jtB6t6tqi7bVLL7Thtsx6XmP37X/dsZQOwGJtTuKSpjUfpcmjVzShFXBiU9J1viinG8PUTZXnQp2iZL3aypYnFKbiDxYpDbNcCGfqzyLb6VQtmjlfOlSoAaGhjTTXfhBy9lvHxvPlRY0hwk9FSOCYoBoRq5WED/pohIxTpRPnQzoW/+XNyErcDL5iN43Z/keob1k5RhPtd8FsNhBwMw+aLVZ27bGjFP3RVQhjoq/shEiMBXsfSYspW9M6AbDvd1xJ6SxD+MHzu7yygylVOrDVJ63A/I2dwitCtteqpger9i50LJqOKRpXt7S0JapOH2eXndWzKykss1RJszRuz3tHR1ANjyuCfmBCAksC1aIXzSOuq1GZiJD6DPVt2HDq7EJ5bzfaLcw8zKyzRKS62fNjOlOBAZhk8+4aEJJtM+hWfEi8mP5BEXwl/N2ENKbJ49WSJMERR7TasGqnhCrwe/MoggRujluP9hfaeM5cOAehjR/dZ3x/aANBQCdKdw91SzjuQtLREg2awoTt0lQDgxyLMdjmnSq+UNc7LGHTT8YbCthbwCUh4i9rB/UW9MGMvCSDyzJ555OPj3xZjiFSdA3c88r0Dq9xrK5dy37KgtQSnmSBuOJPRDEiHlW5tu3kggQBtg285nA1gENYo=
  - secure: lI6o8aKa6vhsIWOVqwQyin/PJORtTebDDNbcm3A1TxUR0IVD/FnV2+PurULggJmrgwcVsPOBu5Pq6ggRq7xZI5qoo0Zw3Vi2zjhKh6yh16AC+4hYfLmXC3SYZJeRZnabsfwVU09crXAKNCiYH21ZqCYhuCcHf5XG2F4jIq7KnDAegwQSVFQxhiRAy3OwmewQ+e3A9NDpWQonzIFrGfszS2onQH1hit0k9IG5y3EchilfkeZnQTsYjklAX7WH8P0wvJMcfao64mnXLLL/H8KdoexHuI7eFQJMeEog5RjzZeNywyB9m9WyGoRrIRzBzg5aRwZlCIEv+pAdYteNyYsOISwBo9nm35K9CK0bqyi94eemsTTJF5ouVshhNOx052Cp5aN1z7a2wVIRAKPXZ+1kNqYaj8jgpdZml7ts1uNt29Wab0KjmKedtYotWy3j+HKLtOi1m6TPfp4WLZu0exUbi3wSCz2E5qi3ONh14jy++l6kAc9/iyKpo9rz+GLonnxsh/9JAiVNc0qTYgVZ/zK0VjYjB4W/jEYEP09dXDc9e0wBMaIxaD7rBPLepmox93rNXa/oc8Twm2cukKTFAc0ScXXrpgG1uDLOcY9vgPCBkrQ+Jq3NcSctr7paU0DrK3hJemB4W1+RHSJALWsEbe1ID+C1XWXyrsPVA6GcIRqMoEg=
  - secure: O/5rtt26jG0k6bJuBQaAp3o0H/WhWbBnFcqVlmhJs7ikLhvyjmRLtoQIS7wLyEcapP6MCrB6PHakZCv3GHzZJb+Q/X+p9slNb532R3x0SlbG2L/xIY6XLqokEhCsE0Lk91u8ArynTqklaXL8phNCtipenA592PwvRkVjy0WfSaTJbLE2xRsD6RMUUaF6q+9LL1H/r8TJ5pQtLeOJhQ7CZYrFM7CZvImB0vr1EBgCr7v+EBeDytlKXxsdzhkgjaXdz07tkw84K8fELNfgZ1QFegTkhgU4PqsQBtHcCHgnfhbiRKxhJ8ojV/wxwF98Ddu737tgeVjw0Dqlk6WiASqGTEhLvU4uCIfMd2rYx23g6r2/IljSrWRviHKFf/GGWVDqSDfSZq9I+TOBWaQNVy6mkaO/vbbIc6+m1/zITlHcpKx5e5QqHTIKg8PI18q/QtTj3kXhooNqHlq6GXw6cEXuqrXW/vv2YYBd+KkWvZ5h5IBUOJd6rTeNbs1JWysSvXMdPnJdpWsbBCB1VpL1N5GlIbxn9U45P+xbvpIsOieKeF0Ld+6u8G4ZNjmRb9fB9+QsqHVbhBozRySbHwz/P2os54Qex/3JsDcAD71vAh76BXR0DgtlHwVimG3Kk+KIBNBNcwPHC+Ve8KTAfSEcpqBNBVLN4jnJhSS3S3au8mXJd2g=
  - secure: Fnmctitup5iXA5zr4EZI2GVyTuNTdgjApg0Hg/4yrRumuXf8Hn1cwsvov2Pp5jzxdueC+bx5p/3O5wZW22qhgFVrldFe3pYhERovbLYDpq5oAe5vfjRkOklEl0a4ZGYCPRqbkXYG9RgEQWmLjcuPdqTQmBqAEViwzj2ENjRufoP2Y6lDURxZPgPsknMH7mZSxHP5oQVVhW+m17dms5nuGcfB9Ziqhbd7B23xHa7onqCRbZnKjQIOCDQbcceCbn9ZNrW4KlkyukJ8Q1d+zcTMdwLJb3Eo2aRQP3By3Zvxqa75hUZmiTaasclSNOC3TSBrV7E7u4wimVXFdbAWxvzwlolmJ3p6nzh5DEsi4ex/R3RxdK5Do0KWGoqCAvV4wmQbu8a8BYLQWSZ5S6GuA3UHFEeU/Sc7Vkb+MEHMlaZaaNMxgygJwLk3xSye5oEnlVLeguET6kcH4m0GR2bhLnjBGirzYpQST/0AIh8P2RZ79Fn7V2PWfVSvVYwfgIScG8uv7Hll34OJJrLSv7B/ZCyZ32YYvIod8TxSt3brl4P2kNgk27p8V7kXWUOnjKO8wiUcI9ARyYWoZOS/PB9Fy5T4YI5C+zHzcO2qgMSPzftzbtvA43bZxFIoO6Z7Hx0iNTeeTCoGG4+2f66BqIG4Xuvcfeht9GcVvByGcDwIld5rRpU=
  - secure: WIUpMWyun9/8hcXoEIIJfZFSKtpGWSxUpMIKCHjlj7jeugxJwha0IIylRBGcjzc2ahUZW5ee6dR/T66ZV0pAsOy/H6XCF+F58Mqhw//w0AdymD6VFPuzegOUbiNeVrXrX/i6NfbVO899go09d+PW5QSzy0C+dsTFltyeaY2Cod9Op0CKQFwtsMMSE0fPnN0HS+NUXyKM1qwYEZ7joARJ1VYHjYWDwA5MsLhJoItXHG6V0RykdJ4v5OmdNl0w/D1zOP6TQ/05Gzl+ZIYrcrBhY6pxcmCtL1tlaiUnkUS3y//kjPvAWFnzK9fUaIo47MwuCrZBcLF0wG7JnU6p5Wam6E9tiYn9pFsB9W79aXTziPhvQyMswV08SIAv1i7v1Fb9qW+Ay96H3BZGP3Q64y8vmul1C1oDOvAQFPmpzqgS02Pgl66N3rli82l1w+PyfdxbVpwDPMQr+eS4+ZxaTHBZFJsc8X8rDHipS3nEr5tKwShZ2GPnt2ohYTy4O1w4YPkLVVtcXhHhZVv/mUhFvFV53tHcfl/zbjvJZ5R2JgCd+nwUphVPJvyXYHrconHtBHE+u7CL0fYCR5UeDB+4CqDodjZGayhMQws8bkP9KMaHPWEiVioqppRKVw3ehSmfIjd+730cEqzMu45O1wwy9m6H8BCNr0M06witXkGEnsIt0ng=
before_install:
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then openssl aes-256-cbc -k "$password"
  -in id_rsa.enc -out deploy_key -d; fi
after_success:
- cd $TRAVIS_BUILD_DIR/scripts
- chmod 755 ghp.sh
- "./ghp.sh"
